### ISSUE TITLE
Developer Friendly directory and file configuration

### ISSUE THREAD

**Issue by meftunca** [ibireme/yyjson#102]
Hi, Compressing the project in 2 files is very bad for developers who are curious and want to develop. I guess you have a decent directory structure. Please share with us

**Comment by ibireme** [comment]
I developed it on these two files as well. I divided the different modules internally with section comments, for example: https://github.com/ibireme/yyjson/blob/350e0cefafb07e284fa93d97d5c3c722a40146b0/src/yyjson.c#L4622-L4631

**Comment by meftunca** [comment]
So, don't you think it would be better to split it into different files? I think the more readable it is, the more developers give more support to the project.

**Comment by ibireme** [comment]
I agree, splitting into different files does make it easier to develop. I just think two files are easier for users to integrate. [cJSON](https://github.com/DaveGamble/cJSON#copying-the-source) is also developed on two files, which I think is fine.

**Comment by meftunca** [comment]
I want to split the project into multiple files and folders if you have permission. I am developing a database focused on machine learning. I need a powerful file handler for my project. Frankly, simdjson was very useful for me, but unfortunately the data change feature was not brought. The library you developed is excellent. I want to create the directory structure in the first stage and integrate a simpler dom structure for cpp in the second part.

Let me tell you why my project needs high speed :). I want to run parallel connected data structures on the collection/document model in nosql architecture like standard sql relationship ties. In short, I need relationship connections as fast as nosql and as strong as sql. I am currently getting 780kb/s per second performance and this score is far better than most sql systems. But my target is 100mb/s.

**Comment by ibireme** [comment]
Sorry, the project is now almost stable and in my opinion, not suitable for making such big changes.

**Comment by meftunca** [comment]
Can I develop a different project that refers to your project?

**Comment by ibireme** [comment]
Of course, I licensed it with MIT, and you can do whatever you want with it.

**Comment by meftunca** [comment]
Thanks for your patience with my questions. You can be sure that I will make it available to everyone in the same way after the new build is finished, my friend :)
