### ISSUE TITLE
Error: An internal error has occurred in the compiler

### ISSUE THREAD

**Issue by Iyiren** [ibireme/yyjson#105]
**Describe the bug**
  Error: An internal error has occurred in the compiler.

**Your environment**
 - OS: [win11]
 - Compiler: [Labwindows cvi 2017]

**Additional context**

**Comment by ibireme** [comment]
LabWindows/CVI is not a common compiler, and I tried to evaluate it for a while.

LabCVI reports that it is based on Clang/LLVM 3.3, but the original clang 3.3 can compile yyjson successfully, so this may indeed be an "internal bug" in LabCVI.

I tried to make some changes and it looks like this compiler has an error when handling too much `__attribute__((always_inline))` under the `Debug` configuration. As a workaround, you can delete the `__attribute__((always_inline))` in `yyjson.h`.
