### ISSUE TITLE
error C2526

### ISSUE THREAD

**Issue by neomissing** [ibireme/yyjson#114]
error C2526: “yyjson_arr_iter_with”: C 链接函数无法返回 C++ 类“yyjson_arr_iter”

**Comment by ibireme** [comment]
Please provide more details, such as OS, compiler version, and how you integrated this library.

**Comment by neomissing** [comment]
WIN11，VS2019 MSVC x64，add_subdirectory(yyjson)

**Comment by ibireme** [comment]
@neomissing Fixed: https://github.com/ibireme/yyjson/commit/fe45385d9842ac3331da576c9e14e2c5b5d1e8a6
