### ISSUE TITLE
Trying to get the raw JSON payload of a yyjson_val object

### ISSUE THREAD

**Issue by eraykoschell** [ibireme/yyjson#123]
I've went through the documentation numerous times and hit a bit of a roadblock; just to point out, my experience with C++ is still very new so I might be overseeing something entirely, however, I hope to get some support here.

**I am trying to get the raw JSON payload as a string of a particular object, however, it keeps saying:**
`0x0000000000000330 <Error reading characters of string.>`

![image](https://github.com/ibireme/yyjson/assets/44278658/30be20a6-cb3c-4793-9e46-211700cadf0b)

The `col` variable is defined as so:
```cpp
yyjson_val* col = yyjson_obj_get(location, heading.c_str());
```

**Here's what I've tried so far:**
- Seeing if there was a problem with the JSON file itself, including running it through a validator to make sure it's compliant.
- Making sure the variables actually exist and the object exists (including the field).

If anyone can guide me with this issue, it would be much appreciated! 😁

_Also, if more information is needed, please do ask._

**Comment by ibireme** [comment]
yyjson does not preserve the original JSON data, so you can't access the raw JSON payload through `col->uni.str`.

The content of `yyjson_val_uni` is determined by the type of `yyjson_val`. For example, `col` is an array, then `col->uni.ofs` stores the offset from this array to the next value. You can find more explanations here: https://github.com/ibireme/yyjson/blob/master/doc/DataStructure.md

If you want to print `col`, you can do this:

```c
const char *str = yyjson_val_write(col, 0, NULL);
// print str
if (str) free(str);
```
