### ISSUE TITLE
Does yyjson support concurrency

### ISSUE THREAD

**Issue by BedRockJie** [ibireme/yyjson#129]
write_dat_to_file 函数在写时没有对文件进行加锁
```c
static bool write_dat_to_file(const char *path, u8 *dat, usize len,
                              yyjson_write_err *err) {
    
#define return_err(_code, _msg) do { \
    err->msg = _msg; \
    err->code = YYJSON_WRITE_ERROR_##_code; \
    if (file) fclose(file); \
    return false; \
} while (false)
    
    FILE *file = fopen_writeonly(path);
    if (file == NULL) {
        return_err(FILE_OPEN, "file opening failed");
    }
    if (fwrite(dat, len, 1, file) != 1) {
        return_err(FILE_WRITE, "file writing failed");
    }
    if (fclose(file) != 0) {
        file = NULL;
        return_err(FILE_WRITE, "file closing failed");
    }
    return true;
    
#undef return_err
}
```
是否考虑加锁以支持并发场景？

**Comment by TkTech** [comment]
The documentation is pretty clear:

> Thread Safety
> 
> The library does not use global variables. Therefore, if you can ensure that the input parameters of a function are thread-safe, then the function calls are also thread-safe.
> 
> In general, [yyjson_doc](https://ibireme.github.io/yyjson/doc/doxygen/html/yyjson_8h.html#structyyjson__doc) and [yyjson_val](https://ibireme.github.io/yyjson/doc/doxygen/html/yyjson_8h.html#structyyjson__val) are immutable and thread-safe, while [yyjson_mut_doc](https://ibireme.github.io/yyjson/doc/doxygen/html/yyjson_8h.html#structyyjson__mut__doc) and [yyjson_mut_val](https://ibireme.github.io/yyjson/doc/doxygen/html/yyjson_8h.html#structyyjson__mut__val) are mutable and not thread-safe.

If you read the API documentation, you'll see that

**Comment by BedRockJie** [comment]
如果存在多进程更新写入同一文件，写函数是否会存在问题？

**Comment by ibireme** [comment]
It is indeed unsafe to write to the same file concurrently. This document also mentions it: https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L1063. 
```
This function is thread-safe when:
 1. The file is not accessed by other threads.
 2. The `alc` is thread-safe or NULL.
```

Windows `LockFileEx()` or Unix `flock()` may ensure the safety of file writing with multi-threading, but these functions are not ANSI C-compliant, so yyjson cannot use them. You can use the function `yyjson_write_fp` and flock()/LockFileEx() to wrap it yourself to meet your needs.
