### ISSUE TITLE
Test failed with clang and valgrind

### ISSUE THREAD

**Issue by ceamac** [ibireme/yyjson#134]
**Describe the bug**
`yyjson` compiled with clang16 `-DYYJSON_BUILD_TESTS=yes -DYYJSON_ENABLE_VALGRIND=yes` fails a test.  With `-DYYJSON_ENABLE_VALGRIND=no` it passes.

**Your environment**
 - OS: Gentoo
 - Compiler: clang 16.0.6

**Additional context**
[LastTest.log.gz](https://github.com/ibireme/yyjson/files/12333032/LastTest.log.gz)

**Comment by ibireme** [comment]
I've tested it and found that gcc-11 and clang-14 work fine, but clang-16 reports this error. Perhaps some change in clang caused this.

https://github.com/ibireme/yyjson/blob/09ccaa449e01879e23f68d8be165e78e65334443/src/yyjson.c#L2554-L2558

There's a struct that is only initialized within a specific branch. If initialize it earlier, the tests will pass. I'll fix it later.

**Comment by ibireme** [comment]
Fixed, now the latest Clang and GCC pass tests: 
https://github.com/ibireme/yyjson/actions/runs/5864670363/job/15900129595

**Comment by ceamac** [comment]
I can confirm the test passes.  Thank you!
