### ISSUE TITLE
Move ownership of a user allocated C string to yyjson object

### ISSUE THREAD

**Issue by CarterLi** [ibireme/yyjson#139]
**Is your feature request related to a problem? Please describe.**

I have a lot of code like

```c
void fillKey(yyjson_mut_doc* doc, yyjson_mut_val* obj, const char* key)
{
  char* str = getAllocatedStringResult(key);
  yyjson_mut_obj_add_strcpy(doc, obj, key, str);
  free(str);
}
```

We have `yyjson_mut_x_add_str(n)cpy` and `yyjson_mut_x_add_str` to add strings. The former api allocates and copies memories, which is sub-optimical. The latter api forces user maintaining the ownership of allocated memories, which is hard to use and generally limited to string literals. 

**Describe the solution you'd like**

I'm propose a new api named `yyjson_mut_x_add_str_moved(doc, x, str)`, which transfer the ownership of str to yyjson ( which means it will be freed when doc gets destroyed ). So that following code works

```c
void fillKey(yyjson_mut_doc* doc, yyjson_mut_val* obj, const char* key)
{
  char* str = getAllocatedStringResult(key);
  yyjson_mut_obj_add_str_moved(doc, obj, key, str);
}
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by CarterLi** [comment]
Can't we use the old pool? If implementing this feature requires introducing additional complexity, I prefer not implementing it.

**Comment by ibireme** [comment]
> Can't we use the old pool? If implementing this feature requires introducing additional complexity, I prefer not implementing it.

The current string pool puts multiple copied strings in a large buffer, so they don't have to be freed one by one when destroyed.

If the strings are not copied, they need to be freed individually, so the existing pool will not work. What do you think?

**Comment by CarterLi** [comment]
So you are imolementing your own malloc

Please careful modifying public structs. It is a ABI imcompartible change.

**Comment by ibireme** [comment]
> So you are implementing your own malloc. Will the memory be reused if a string is removed from yyjson mut doc?

No, the existing pool implementation is quite basic. It only grows and doesn't reuse, and it's mainly used to optimize building JSON.

> Please careful modifying public structs. It is a ABI imcompartible change.

It seems to be more complex than I had initially anticipated. If you and others don't have a strong need for this feature, I believe it's best to hold off on making this change for now.

**Comment by CarterLi** [comment]
> No, the existing pool implementation is quite basic. It only grows and doesn't reuse, and it's mainly used to optimize building JSON.

Most malloc implementation already uses memory pool. You generally won't get much benefit by implementing your own.

> It seems to be more complex than I had initially anticipated. If you and others don't have a strong need for this feature, I believe it's best to hold off on making this change for now.

Agreed.
