### ISSUE TITLE
Static Code Analysis: Identical sub-expressions on both sides of operator "<<"

### ISSUE THREAD

**Issue by sniper00** [ibireme/yyjson#144]
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L741C74-L741C74

https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L1070

Using the same value on both sides of a binary operator is a code defect. In the case of logical operators, it is either a copy/paste error and, therefore, a bug, or it is simply duplicated code and should be simplified. In the case of most binary mathematical operators, having the same value on both sides of an operator yields predictable results and should be simplified as well.

**Comment by ibireme** [comment]
Thanks, fixed.
