### ISSUE TITLE
Json files are not newline terminated when pretty printing

### ISSUE THREAD

**Issue by u3shit** [ibireme/yyjson#147]
**Describe the bug**
When writing a json file using `yyjson_mut_write_fp` (and probably others but I haven't tested them), even when using `YYJSON_WRITE_PRETTY` or `YYJSON_WRITE_PRETTY_TWO_SPACES`, the resulting file will have no newline at the end. While it might be justifiable with minimized output, according to POSIX, these are not text files (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403 and https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) which produce various problems when trying to use these files. E.g. if you `cat` one of these files, the closing `}` will end up before your shell prompt but the shell will think it's not there and mess up cursor movement commands, diff files will have an ugly `\ No newline at end of file` at the end, busybox based utilities sometimes ignore the last line in these files (which is technically correct, since you're feeding binary garbage into an utility that expects a text file), etc.

**Your environment**
 - OS: Gentoo Linux amd64
 - Compiler: gcc 13.2.1

**Comment by ibireme** [comment]
Most JSON libraries don't add a newline at the end of JSON files. It's a topic that's been talked about, like here: [Why is json.dump not ending the line with '\n'?](https://stackoverflow.com/questions/54716132/why-is-json-dump-not-ending-the-line-with-n).

If you want, we can add a new option to control it, like `YYJSON_WRITE_NEWLINE_AT_END `.
