### ISSUE TITLE
How to change the object key in mutable object?

### ISSUE THREAD

**Issue by Edwardmark** [ibireme/yyjson#153]
Hi, if I want to change the json:
{
  "a": [123. 456]
}
to 
{
  "a_copy": [123,456]
}

how to use the yyjson api to to that? Thanks in advance.

**Comment by ibireme** [comment]
https://github.com/ibireme/yyjson/blob/82ea88337ba6b70c663fdce414d2731451b1de3a/src/yyjson.h#L3765-L3791

**Comment by Edwardmark** [comment]
@ibireme Thanks. It works.
