### ISSUE TITLE
A character make fail the JSON (empty JSON)

### ISSUE THREAD

**Issue by lgg2** [ibireme/yyjson#157]
Hello,

A value contening 'º' (0xb0 / U+00B0) abort the JSON write, giving the error:
Error: 7
"invalid utf-8 encoding in string"

**Comment by ibireme** [comment]
The character 'º' needs two bytes in UTF-8: [0xC2 0xB0]. Just [0xB0] isn't a valid UTF-8 encoding. 
See: https://www.compart.com/en/unicode/U+00B0
