### ISSUE TITLE
Does yyjson have parameters to set decimal places?

### ISSUE THREAD

**Issue by wang21825227** [ibireme/yyjson#158]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ibireme** [comment]
No, yyjson writes floating point numbers using the `Schubfach` algorithm, which converts floating point numbers to the shortest possible decimal representation.

**Comment by wang21825227** [comment]
Will you consider supporting setting this writing parameter later?

**Comment by ibireme** [comment]
I'll consider supporting it in the future, but it's not a high priority at the moment. 

Implementing this feature would require rewriting the internal float-point writing algorithm, which could be complex and may affect performance.

**Comment by jagoly** [comment]
A potentially simpler feature that I would like is the ability to write out numbers as if they were 32 bit floats. In my project (a game), all of my real numbers are 32 bit. I've got an editor that can edit things and write out json, but converting values from floats to doubles results in nice short values like 0.8 instead being written out as 0.800000011920929.

**Comment by ibireme** [comment]
Done: https://github.com/ibireme/yyjson/commit/6d416047822d86d53a3a0b45a6a5abf28383a1dc
