### ISSUE TITLE
Adds a key-value pair at the end of the object.(yyjson_mut_obj_add)

### ISSUE THREAD

**Issue by idewindy** [ibireme/yyjson#16]
Can you add a method without changing its position？
 For example yyjson_mut_obj_replace

**Comment by lyjdgkg** [comment]
yyjson_api_inline bool yyjson_mut_obj_replacen(yyjson_mut_val* obj,
	const char* key_str,
	size_t key_len,
	yyjson_mut_val* val) {
	if (yyjson_likely(key_str && key_len)) {
		size_t len = yyjson_mut_obj_size(obj);
		if (yyjson_likely(len)) {
			uint64_t tag = (((uint64_t)key_len) << YYJSON_TAG_BIT) | YYJSON_TYPE_STR;
			yyjson_mut_val* key = ((yyjson_mut_val*)obj->uni.ptr)->next->next;
			while (len-- > 0) {
				if (key->tag == tag &&
					memcmp(key->uni.ptr, key_str, key_len) == 0) {
					val->next = key->next->next;
					key->next = val;
					return true;
				}
				key = key->next->next;
			}
		}
	}
	return false;
}

**Comment by lyjdgkg** [comment]
`yyjson_api_inline bool yyjson_mut_obj_replacen(yyjson_mut_val* obj,
	const char* key_str,
	size_t key_len,
	yyjson_mut_val* val) {
	if (yyjson_likely(key_str && key_len)) {
		size_t len = yyjson_mut_obj_size(obj);
		if (yyjson_likely(len)) {
			uint64_t tag = (((uint64_t)key_len) << YYJSON_TAG_BIT) | YYJSON_TYPE_STR;
			yyjson_mut_val* key = ((yyjson_mut_val*)obj->uni.ptr)->next->next;
			while (len-- > 0) {
				if (key->tag == tag &&
					memcmp(key->uni.ptr, key_str, key_len) == 0) {
					val->next = key->next->next;
					key->next = val;
					return true;
				}
				key = key->next->next;
			}
		}
	}
	return false;
}`

**Comment by lyjdgkg** [comment]
`
yyjson_api_inline bool yyjson_mut_obj_replacen(yyjson_mut_val* obj,
	const char* key_str,
	size_t key_len,
	yyjson_mut_val* val) {
	if (yyjson_likely(key_str && key_len)) {
		size_t len = yyjson_mut_obj_size(obj);
		if (yyjson_likely(len)) {
			uint64_t tag = (((uint64_t)key_len) << YYJSON_TAG_BIT) | YYJSON_TYPE_STR;
			yyjson_mut_val* key = ((yyjson_mut_val*)obj->uni.ptr)->next->next;
			while (len-- > 0) {
				if (key->tag == tag &&
					memcmp(key->uni.ptr, key_str, key_len) == 0) {
					val->next = key->next->next;
					key->next = val;
					return true;
				}
				key = key->next->next;
			}
		}
	}
	return false;
}
`

**Comment by lyjdgkg** [comment]
yyjson_api_inline bool yyjson_mut_obj_replacen(yyjson_mut_val* obj,
	const char* key_str,
	size_t key_len,
	yyjson_mut_val* val) {
	if (yyjson_likely(key_str && key_len)) {
		size_t len = yyjson_mut_obj_size(obj);
		if (yyjson_likely(len)) {
			uint64_t tag = (((uint64_t)key_len) << YYJSON_TAG_BIT) | YYJSON_TYPE_STR;
			yyjson_mut_val* key = ((yyjson_mut_val*)obj->uni.ptr)->next->next;
			while (len-- > 0) {
				if (key->tag == tag &&
					memcmp(key->uni.ptr, key_str, key_len) == 0) {
					val->next = key->next->next;
					key->next = val;
					return true;
				}
				key = key->next->next;
			}
		}
	}
	return false;
}

**Comment by hellozhuzhu** [comment]
类似这个？
`
yyjson_api_inline bool unsafe_yyjson_mut_obj_replace(yyjson_mut_val *obj,
                                                                                       yyjson_mut_val *key,
                                                                                       yyjson_mut_val *val) {
    size_t key_len = unsafe_yyjson_get_len(key);
    size_t obj_len = unsafe_yyjson_get_len(obj);
    if (obj_len) {
        yyjson_mut_val *pre_key = (yyjson_mut_val *)obj->uni.ptr;
        yyjson_mut_val *cur_key = pre_key->next->next;
        size_t i;
        for (i = 0; i < obj_len; i++) {
            if (key->tag == cur_key->tag &&
            memcmp(key->uni.str, cur_key->uni.ptr, key_len) == 0) {
                size_t cpy_len = sizeof(*key) - sizeof(key->next);
                yyjson_mut_val tmp;
                memcpy(&tmp, cur_key, cpy_len);
                memcpy(cur_key, key, cpy_len);
                memcpy(key, &tmp, cpy_len);

                memcpy(&tmp, cur_key->next, cpy_len);
                memcpy(cur_key->next, val, cpy_len);
                memcpy(val, &tmp, cpy_len);
                return true;
            } else {
                pre_key = cur_key;
                cur_key = cur_key->next->next;
            }
        }
    }
    return false;
}
`
测试代码如下：
`
#include <stdio.h>
#include "yyjson.h"

#define INDEX_STR        "index"
#define INDEX_STR_LEN    5
#define HTTP_STR         "http"
#define HTTP_STR_LEN     4
#define HTTP_NEW_STR     "http_new"
#define HTTP_NEW_STR_LEN 8

int main()
{
    yyjson_mut_doc *doc = yyjson_mut_doc_new(NULL);
    yyjson_mut_val *root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);
    yyjson_mut_obj_add_strn(doc, root, INDEX_STR, HTTP_STR, HTTP_STR_LEN);

    yyjson_mut_val *key = yyjson_mut_strn(doc, INDEX_STR, INDEX_STR_LEN);
    yyjson_mut_val *http = yyjson_mut_strn(doc, HTTP_NEW_STR, HTTP_NEW_STR_LEN);
    yyjson_mut_obj_replace(root, key, http);

    char *json_str = yyjson_mut_write(doc, 0, NULL);
    printf("json str :%s\r\n", json_str);
    free(json_str);
    yyjson_mut_doc_free(doc);
    return 0;
}

`

**Comment by ibireme** [comment]
Added by  hellozhuzhu: https://github.com/ibireme/yyjson/pull/32

**Comment by idewindy** [comment]
Too good, thank you very much
