### ISSUE TITLE
Remove static qualifiers to support wrapping in other languages 

### ISSUE THREAD

**Issue by nordlow** [ibireme/yyjson#165]
I'm currently developing a wrapper for yyjson in D.

However the inline qualifier macro(s) on some API functions prevents them from being callable as an extern(C) functions. Would it possible to remove the static qualifer part in those macros?

**Comment by TkTech** [comment]
No part of the public API should be marked as inline, what are you trying to wrap?

**Comment by ibireme** [comment]
Maybe you could try this:

```c
// create a new file, e.g. yyjson_ext.c
#define yyjson_api_inline yyjson_api
#include yyjson.h
```

**Comment by nordlow** [comment]
Search for `yyjson_api_inline` in `yyjson.h`.

**Comment by nordlow** [comment]
I suggest changing

```c
#ifndef yyjson_api_inline
#   define yyjson_api_inline static yyjson_inline
#endif
```

to

```c
#ifndef yyjson_api_inline
#   define yyjson_api_inline yyjson_inline
#endif
```

in `yyjson.h`.

**Comment by ibireme** [comment]
@nordlow No, the `static` keyword is used to limit the scope of these functions to the current source file. If we simply remove `static` and make these functions inline, it could potentially lead to naming collisions and linker errors in some environments.

**Comment by AlexKlo** [comment]
Hello, @ibireme @nordlow 

I also encountered issues when trying to wrap yyjson in a Julia package. After compiling the dynamic library, I am unable to call functions like yyjson_read, yyjson_doc_get_root, yyjson_get_str, etc. These functions use the yyjson_api_inline macro. Does this mean that these functions are not public? Is there a way to compile the library so that all functions with yyjson_api_inline are accessible?

**Comment by ibireme** [comment]
@AlexKlo `yyjson_api_inline` is actually `static inline`, so these functions do not export symbols. 
If you want to export symbols, I still recommend you try this approach:

```c
// create a new file, e.g. yyjson_ext.c
#define yyjson_api_inline yyjson_api
#include yyjson.h
```

**Comment by John-Colvin** [comment]
You can also of course force it from the compiler command line, e.g. `-Dyyjson_api_inline=yyjson_api` or tell cmake to do the same.

**Comment by nordlow** [comment]
> -Dyyjson_api_inline=yyjson_api

Excellent!

See https://github.com/nordlow/yyjson-d/commit/a92a4fabe30831929c6593985daa3b7f398b4758.
