### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by CarterLi** [ibireme/yyjson#168]
As discussed in https://github.com/ibireme/yyjson/issues/166#issuecomment-2102133003

> We are reporting `unexpected character`, which is a general error and may not be very helpful. Can we report what charactor yyjson expects?

>
> For example: https://github.com/fastfetch-cli/fastfetch/issues/866#issuecomment-2094258422

>
> Can we report a comma is expected?

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/yyjson/commit/9b2c8b216a3672c5267714f7131b1ce84dcf77d4
