### ISSUE TITLE
modify json, then save, But Japanese and Chinese changed to Unicode

### ISSUE THREAD

**Issue by idewindy** [ibireme/yyjson#17]
绿帽子节 to \u7EFF\u5E3D\u5B50\u8282
I run it on iOS

**Comment by ibireme** [comment]
It seems that you add `YYJSON_WRITE_ESCAPE_UNICODE` flag when serializing JSON?

**Comment by idewindy** [comment]
I just took a look, yes 🤦‍♂️ It's all a pot of copying
