### ISSUE TITLE
Condition for calling read_number_raw

### ISSUE THREAD

**Issue by danielaparker** [ibireme/yyjson#170]
There must have been a reason for using

```cpp
    /* read number as raw string if has `YYJSON_READ_NUMBER_AS_RAW` flag */
    if (unlikely(pre && !has_read_flag(BIGNUM_AS_RAW))) {
        return read_number_raw(ptr, pre, flg, val, msg);
    }
```
rather than simply
```cpp
    if (unlikely(has_read_flag(READ_NUMBER_AS_RAW))) {
        return read_number_raw(ptr, pre, flg, val, msg);
    }
```
but I don't see it.

One, it doesn't seem to be in the spirit of yyjson to do two checks where one will do.

Two, the documentation for `YYJSON_READ_BIGNUM_AS_RAW` states "The flag will be overridden by `YYJSON_READ_NUMBER_AS_RAW`  flag." But with this code, it's the other way around, if `YYJSON_READ_BIGNUM_AS_RAW | YYJSON_READ_NUMBER_AS_RAW` is passed as flags, it's `YYJSON_READ_BIGNUM_AS_RAW` that overrides `YYJSON_READ_NUMBER_AS_RAW`.

It's a precondition that `pre` is not null before the call to `read_number_raw`, but that's already guaranteed if either of the flags are set.

All tests still pass with the alternative check.

**Comment by ibireme** [comment]
Thanks for your insight!
This condition was [added](https://github.com/ibireme/yyjson/commit/f2525dcb2390243555b5fa4cafcf689e618d990e#diff-dcbeb2b4040ebe3581151c96f4a1355abc3962a11c2704937b52c90423904d7cL4260-R4270) along with `YYJSON_READ_BIGNUM_AS_RAW`, but it doesn't match the documentation. 
This should be considered a bug and not covered by the tests.

**Comment by ibireme** [comment]
Fixed
