### ISSUE TITLE
Tested against "Parsing JSON is a Minefield" test suite?

### ISSUE THREAD

**Issue by fingolfin** [ibireme/yyjson#180]
I was wondering how robust this JSON library is. The most comprehensive document on this topic I know still is https://seriot.ch/projects/parsing_json.html and the associated test suite https://github.com/nst/JSONTestSuite

I was wondering if anyone tried to run this library through that test suite and see if it avoids the various crashes and other pitfalls that can occur there?

**Comment by ibireme** [comment]
Yes, the JSONTestSuite is already included in the current test suite: 
https://github.com/ibireme/yyjson/blob/3dc44414d3c5550479478a53fa9987e0d102a15e/test/test_json_reader.c#L216-L263

**Comment by fingolfin** [comment]
awesome, thank you!
