### ISSUE TITLE
yyjson_mut_obj_add_val does not accept key length

### ISSUE THREAD

**Issue by marsgpl** [ibireme/yyjson#185]
**Is your feature request related to a problem? Please describe.**

I want to create the following JSON string: `{"\u0000hi":"\u0001"}`
Root object key `"\0hi"` starts with a nul byte.
I can't find the API method that allows me to provide my key length.
`yyjson_mut_obj_add_func` derives my key length via `strlen(_key)`, which breaks on nul byte, making it impossible to add such keys to the json string.

**Describe the solution you'd like**

I've submitted a pull request providing a new function: `yyjson_mut_obj_add_keyn_val` and a macro `yyjson_mut_obj_add_keyn_func`.
I did not implement the whole family of obj_add_*.

**Describe alternatives you've considered**

Alternative is to define these new macros in a consumer code, which might break on next yyjson update, therefore unreliable.

**Additional context**

pr: https://github.com/ibireme/yyjson/pull/186
usage: https://github.com/marsgpl/furiend/blob/d0c360e25717533556e77df4500e3f9668fa1a30/src/lua-lib/json/json.c#L143

**Comment by ibireme** [comment]
Thanks for the suggestion.

The `yyjson_mut_obj_add_xxx()` functions are just wrappers around `yyjson_mut_obj_add()` for easier use. Adding a whole new set of `yyjson_mut_obj_add_keyn_xxx()` functions seems too complex.

Instead of adding new functions, I'd suggest doing this:

```c
yyjson_mut_obj_add(obj, yyjson_mut_strn(doc, key, key_len), val);
```

**Comment by marsgpl** [comment]
> Instead of adding new functions, I'd suggest doing this:
> ```c
> yyjson_mut_obj_add(obj, yyjson_mut_strn(doc, key, key_len), val);
> ```

thank you, I didn't spot `yyjson_mut_obj_add` at first.
it makes sense, will switch to it.
problem solved, pr and ticket are safe to close.
