### ISSUE TITLE
YYJSON_FLAGS not working correctly under MSVC

### ISSUE THREAD

**Issue by Antares0982** [ibireme/yyjson#189]
**Describe the bug**
CMake concats all `YYJSON_FLAGS` as one compiler option and passes it to `cl`.
You can reproduce this simply with `-DYYJSON_ENABLE_FASTMATH=ON`

```
cl : 命令行  warning D9002: 忽略未知选项“/utf-8 /fp:fast”
```

The actual `fp` flag fallbacks to default flag `fp:precise`

**Your environment**
 - OS: Win11 24H2
 - Compiler: MSVC, cl 19.42.34435
 - CMake: 3.31.2

**Comment by ibireme** [comment]
Fixed
