### ISSUE TITLE
Enhanced control of number formatting for minified serialization to retain accuracy

### ISSUE THREAD

**Issue by chad-earthscope** [ibireme/yyjson#190]
I'm creating JSON with large uint64_t values like such:
```
yyjson_mut_obj_add_uint (doc, val, "large_uint", (uint64_t) 18446744073709551614ULL);
```

With `yyjson_mut_write (doc, 0, NULL);`, the result is:
```
"large_uint": 1.8446744073709552e+19,
```

This real value treatment is clearly losing accuracy of the actual value.

However, with `yyjson_mut_write (doc, YYJSON_WRITE_PRETTY, NULL);`, the result is:
```
"large_uint": 18446744073709551614,
```

which is excellent and retains the value that I need to be exact.  

What I want is an option to write _minified_ JSON that retains the accuracy of large values like this.  Clearly it's possible, given the "pretty" output.

Thanks for considering.

**Comment by ibireme** [comment]
Please check the actual code. If the same `val` is added to multiple containers, or if the `doc` to which a val belongs is freed, it might lead to some undefined behavior.

**Comment by chad-earthscope** [comment]
Appologies, this was user error.  The code I'm working on is a web service and I was reading the JSON in a browser, but the browser's "pretty print" option was converting the value to an expoential format.  Lesson learned, look at the raw data.  Sorry for the noise.
