### ISSUE TITLE
yyjson.h: need to properly compile with -Wundef compiler option

### ISSUE THREAD

**Issue by pavelxdd** [ibireme/yyjson#20]
The header file `yyjson.h` has multiple issues when compiling with `-Wundef` compiler option on GCC or clang.

There are missing check if `_MSC_VER` or `__GNUC__` or other flags are defined before checking them.

Example lines:
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L127
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L131
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L168
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L177
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L187
https://github.com/ibireme/yyjson/blob/master/src/yyjson.h#L205

**Comment by ibireme** [comment]
Fixed~
