### ISSUE TITLE
How to serialize and deserialize JSON with sub-object arrays like this?

### ISSUE THREAD

**Issue by Arcbug** [ibireme/yyjson#27]
Example 1:
```json
{
	"deviceId":"11223344",
	"eventType":"Alarm",
	"value":
	[
	    {
	        "type":"heart",
	        "upperLimit":"10:00:00",
	        "lowerLimit":"15:04:00"
	    }, 
	    {
	        "type":"heart",
	        "upperLimit":"17:01:00",
	        "lowerLimit":"21:15:00"
	    }
      ]
}
```

Example 2:
```json
{
    "deviceId":"11223344",
    "eventType":"deviceEvent",
    "value":
    [
        {
            "type":"online",
            "value":"yes"
        }
    ]
}
```
一般的JSON解析用您的yyjson库非常方便，但是这种复杂点的没有例子，不会用了，希望作者能在百忙中回复一下

**Comment by Arcbug** [comment]
就像您在文档中JSON Pointer举的这个例子，
{
    "size" : 3,
    "users" : [
        {"id": 1, "name": "Harry"},
        {"id": 2, "name": "Ron"},
        {"id": 3, "name": "Hermione"}
    ]
}
怎么调用才能序列化成例子这样呢？

**Comment by ibireme** [comment]
Please read the documentation first.

To read the JSON:
```c
...
    yyjson_val *root = yyjson_doc_get_root(doc);
    yyjson_val *array = yyjson_obj_get(root, "value");
    size_t idx, max;
    yyjson_val *one;
    yyjson_arr_foreach(array, idx, max, one) {
        const char *type = yyjson_get_str(yyjson_obj_get(one, "type"));
        const char *value = yyjson_get_str(yyjson_obj_get(one, "value"));
    }
```

To write the JSON:
```c
    yyjson_mut_doc *doc = yyjson_mut_doc_new(NULL);
    
    yyjson_mut_val *root = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_str(doc, root, "eventType", "Alarm");
    
    yyjson_mut_val *array = yyjson_mut_arr(doc);
    yyjson_mut_obj_add_val(doc, array, "value", array);
    
    yyjson_mut_val *one = yyjson_mut_arr_add_arr(doc, array);
    yyjson_mut_obj_add_str(doc, one, "type", "online");
    yyjson_mut_obj_add_str(doc, one, "value", "yes");
    
    yyjson_mut_doc_set_root(doc, root);
    
    const char *json = yyjson_mut_write(doc, YYJSON_WRITE_PRETTY, NULL);
```

**Comment by Arcbug** [comment]
经调试发现：
yyjson_mut_obj_add_val(doc, array, "value", array);
yyjson_mut_obj_add_str(doc, one, "type", "online");
yyjson_mut_obj_add_str(doc, one, "value", "yes");
这几个函数都返回了false。

看源代码应该是：
#define yyjson_mut_obj_add_func(func) \
    if (yyjson_likely(doc && yyjson_mut_is_obj(obj) && _key)) \
	{ \
        yyjson_mut_val *key = unsafe_yyjson_mut_val(doc, 2); \
        if (yyjson_likely(key)) \
		{ \
            size_t len = unsafe_yyjson_get_len(obj); \
            yyjson_mut_val *val = key + 1; \
            key->tag = YYJSON_TYPE_STR | YYJSON_SUBTYPE_NONE; \
            key->tag |= (uint64_t)strlen(_key) << YYJSON_TAG_BIT; \
            key->uni.str = _key; \
            func \
            unsafe_yyjson_set_len(obj, len + 1); \
            unsafe_yyjson_mut_obj_add(obj, key, val, len); \
            return true; \
        } \
    } \
    return false;
里面第二行的 yyjson_mut_is_obj(obj)无法判断YYJSON_TYPE_ARR类型导致的，试着替换成yyjson_mut_is_ctn判断，这样几个函数可以返回true了，但是运行后还是得到：{{\LF "eventType": "Alarm"\LF}}，无法出现value的对象内容

**Comment by ibireme** [comment]
Oh, I made a mistake, try this:

```c
    yyjson_mut_val *array = yyjson_mut_arr(doc);
    yyjson_mut_obj_add_val(doc, root, "value", array);
    
    yyjson_mut_val *one = yyjson_mut_arr_add_obj(doc, array);
    yyjson_mut_obj_add_str(doc, one, "type", "online");
    yyjson_mut_obj_add_str(doc, one, "value", "yes");
```

**Comment by Arcbug** [comment]
谢谢，可以得到我想要的结果了，也不是yyjson_mut_is_obj(obj)的原因，确实如您所说。
void OnLine_Json_Test(void)
{
	yyjson_mut_doc *doc = yyjson_mut_doc_new(NULL);
    
    yyjson_mut_val *root = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_str(doc, root, "eventType", "Alarm");

    yyjson_mut_val *array = yyjson_mut_arr(doc);
	
    yyjson_mut_obj_add_val(doc, root, "value", array);//这个地方第2个参数要把array改成array
	
    yyjson_mut_val *one = yyjson_mut_arr_add_obj(doc, array);//要把yyjson_mut_arr_add_arr改成yyjson_mut_arr_add_obj
    yyjson_mut_obj_add_str(doc, one, "type", "online");
	yyjson_mut_obj_add_str(doc, one, "value", "yes");
	
    yyjson_mut_doc_set_root(doc, root);

    const char *json = yyjson_mut_write(doc, YYJSON_WRITE_PRETTY, NULL);
	if (json) 
	{
		printf("json: %s\n", json); 
		free((void *)json);
	}
	yyjson_mut_doc_free(doc);	
}

**Comment by Arcbug** [comment]
谢谢郭大神，您写的yyjson真好用，感觉比cjson等好用多了，调用起来通俗易懂，简洁明了，使用方便。
做为一个工作十多年的c语言工程师，佩服！
