### ISSUE TITLE
VS2017 compile error

### ISSUE THREAD

**Issue by qs991011** [ibireme/yyjson#29]
I use msvc generate yyjson，when I conpile this ,I found some errors.

![QQ图片20210603103138](https://user-images.githubusercontent.com/15025829/120577465-f6b1a180-c456-11eb-83ca-e8df5202bce1.png)

**Comment by ibireme** [comment]
Maybe you should disable the `Precompiled Headers` in your project configuration,
You can also use CMake or vcpkg to integrate it with your project.

**Comment by qs991011** [comment]
yes，I use CMake generate the project. But when I use the lastest source code , These errors  disappear.and previous source code still show errors.
