### ISSUE TITLE
The yyjson_obj_getn function increases the range limit.

### ISSUE THREAD

**Issue by ghost** [ibireme/yyjson#39]
The yyjson_obj_getn function requires linear search time when searching. Whether to consider increasing the range and limiting the start position and end position of the search, so that all node traversals caused by expandable fields can be avoided during use.

**Comment by hellozhuzhu** [comment]
Or whether to consider using a hashmap structure to store key-value pairs.

**Comment by ibireme** [comment]
Build a hashmap during parsing may cost too much time. If you need to query an object multiple times, you may build your hashmap after parsing.

If the order of object's key is known at compile time, you can use this method to avoid searching the entire object:
```c
// { "x":1, "y":2, "z":3 }
yyjson_val *obj = ...;
yyjson_obj_iter iter;
if (yyjson_obj_iter_init(obj, &iter)) {
    yyjson_val *x = yyjson_obj_iter_get(&iter, "x");
    yyjson_val *y = yyjson_obj_iter_get(&iter, "y");
    yyjson_val *z = yyjson_obj_iter_get(&iter, "z");
}
```
