### ISSUE TITLE
Use Schubfach way instead of Ryu for faster serialization of floating point numbers

### ISSUE THREAD

**Issue by plokhotnyuk** [ibireme/yyjson#4]
1. [Giulietti, "The Schubfach way to render doubles"](https://drive.google.com/open?id=1luHhyQF9zKlM8yJ1nebU0OgVYhfC6CBN)
2. [Author's sources with a license](https://github.com/c4f7fcce9cb06515/Schubfach/blob/master/todec/src/math/DoubleToDecimal.java)
3. [The Schubfach algorithm adoption in the jsoniter-scala library](https://github.com/plokhotnyuk/jsoniter-scala/blob/c269579440f3638ad43fc1f1c4d499319630cbc8/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1833-L2038)
4. [C++ implementation of the Schubfach algorithm from Alexander Bolz](https://github.com/abolz/Drachennest/blob/master/src/schubfach_64.cc)

**Comment by ibireme** [comment]
Thanks, this is already in the TODO list.
I have a benchmark project: https://github.com/ibireme/c_numconv_benchmark , the `Schubfach`'s result is excellent.

**Comment by ibireme** [comment]
The speed of serializing `canada.json` has increased from 0.472 GB/s to 0.541 GB/s (GCC9.3, Intel NUC8i5).
