### ISSUE TITLE
Recursively parse an array of json objs

### ISSUE THREAD

**Issue by ghost** [ibireme/yyjson#51]
Hi!

I was just testing the library for the first time and couldn't find a way to parse something like the following:

{"people": [ {"name":"Alice", "age": 40}, {"name": "John", "age": 38} ]}

Is there a (optimal) way to do it?
Can you please provide an example on how to just iterate over multiple objs inside the array and print the "name" and "age"?

Thank you in advance!

**Comment by uvuxz** [comment]
Second (and last) follow-up question.

On the previous example, assume that "age" can either be an integer or a float.
I have tried 
> yyjson_get_real(yyjson_obj_get(one, "age")
and it only works if it is a floating point and returns zero if age is an integer.

Now assume that you would always want to store "age" as a float/double, would it be necessary to check both functions yyjson_get_real, yyjson_get_int, and convert the result of the latter to (double) or is it possible to parse directly to double, even if the value is an int?

Thank you. :)
