### ISSUE TITLE
Questions about the implemenation of f64_bin_to_dec

### ISSUE THREAD

**Issue by FrankHB** [ibireme/yyjson#54]
https://github.com/ibireme/yyjson/blob/19220b1194a2dab2bbbc176dac485ffd8b8bb037/src/yyjson.c#L5712-L5717

1. The code is inconsistent to the comment. Which is the `lower_bound_closer` case? Refer to the shorter interval case in the Dragonbox paper, I believe the code is more correct than the comment.

2. How does `131237` come? It seems not the best magic, although already works for [-1074, 971] with u = 20. (When u = 20, even the best one may fail with e = -1335.)

**Comment by ibireme** [comment]
As mentioned in the comments, this implementation comes from `Schubfach`:
https://github.com/abolz/Drachennest/blob/master/src/schubfach_64.cc

**Comment by FrankHB** [comment]
1. This implementation is different from the original Schubfach in various details. Now I see the the upstream source is more relevant than the papers. In the Schubfach papers (all versions), this is called "irregular spacing". In the Dragonbox paper, this is called the "shorter interval case". Both are not syntactically close to the wording here.) Perhaps the comments on implementation can be improved, or there can be some clarification to emphasize the adoption of the direct upstream (by abolz). And at least the confusing comments on the computation at current should be fixed.

2. I'm still curious how to figure out magic numbers like `131237`. The original Schubfach papers provide some other approximations I believe not optimal like abolz's and your implementations. Nevertheless, the papers have the explanation to show the correctness, and different magics deserve separate proofs, in particular that your implementation is also different to abolz's.

3. Another divergence from the original Schubfach papers is the computation of the parameter `h`. This is quite implicit. I've spent hours to find out the reason is the fact of table entry format: Schubfach uses 2 Java signed `long` (126-bit), but the abolz's and your implementations have an effective 127-bit format. Strictly speaking, this is an upstream issue, but adding some comments here may also make things better.

I'm trying working on [my own `dtoa`](https://github.com/FrankHB/YSLib/blob/768c9f0fa80c8532b4d6f0f2c5b06b8033df368c/YFramework/source/NPL/NPLAMath.cpp#L3775) for types not only `double` (without table by default; still quite buggy, e.g. wrong condition for shorter interval case + wrong assumption on hidden bit + `long double` crash on x86-64 gcc 11.1 -O3 + suboptimal internal computation with or without tables), so I hope there can be more robust reasoning in the current implementations for reference.

**Comment by FrankHB** [comment]
BTW, one more implementation question irrelevant to the topic here: I see the "real GCC" detection... is there any reason to use `asm` specifically for GCC? Any links to GCC bugs?

**Comment by FrankHB** [comment]
Another issue, perhaps derserving a separate issue:

> Since yyjson is ANSI C compatible, no other configuration is needed typically.

Well, ANSI C has very, very weak rules on the floating-point format unless IEC 60559 is guaranteed to follow: there is no guarantee on bit-patterns of floating-point values, so bitmask tricks to extract the layout may simply stop to work for some peculiar (but still compatible to ANSI C) implementations. (At my best effort, I doubt the detection of hidden bit is feasible in strictly conforming C or C++.)

Your fast math detection does some good in the best effort manner to prevent such failure, however:

* `#warning` is not conforming. It may fail with `-pedantic`. (OK, this might be the intended behavior, actually.)
* `__USE_FAST_MATH__` seems [not reliable](https://reviews.llvm.org/D20481).
* What about MSVC `/fp:fast` and `_M_FP_FAST`?
* GCC's `-ffinite-math-only` would be enough to break things up, not captured by `__FAST_MATH__`.

There are rooms of improvements on both the code and the documentation.

**Comment by ibireme** [comment]
Thanks for your feedback.

> This implementation is different from the original Schubfach in various details. Now I see the the upstream source is more relevant than the papers: in the Schubfach papers (all versions), this is called "irregular spacing"; in the Dragonbox paper, this is called the "shorter interval case"; both are not syntactically close to the wording here. Perhaps the comments on implementation can be improved, or there can be some clarification to emphasize the adoption of the direct upstream (by abolz). And at least the confusing comments on the computation at current should be fixed.

It's true that quite a lot of code lacks comments. I will read the paper again and improve these comments, hoping that the comments will be more accurate and easier to understand.

> I'm still curious how to figure out magic numbers like `131237`. The original Schubfach papers provide some other approximations I believe not optimal like abolz's and your implementations. Nevertheless, the papers have the explanation to show the correctness, and different magics deserve separate proofs, in particular that your implementation is also different to abolz's.

I simply tried a brute force search to see if there's a better choice when outputting the same result over a range of possible inputs. Since I only need to process 64-bit fp numbers, while other implementations need to process 16/32/128-bit fp numbers.

> Another divergence from the original Schubfach papers is the computation of the parameter `h`. This is quite implicit. I've spent hours to find out the reason is the fact of table entry format: Schubfach uses 2 Java signed `long` (126-bit), but the abolz's and your implementations have an effective 127-bit format. Strictly speaking, this is an upstream issue, but adding some comments here may also make things better.

The lookup table I used here is a bit different from either the paper or the abolz implementation. The main reason is that I want to share this LUT for both parsing and printing to reduce the binary size.

**Comment by ibireme** [comment]
> BTW, one more implementation question irrelevant to the topic here: I see the "real GCC" detection... is there any reason to use `asm` specifically for GCC? Any links to GCC bugs?

The instructions generated by GCC are correct, but the performance is slightly worse.

I want to reduce the number of instructions when reading consecutive characters. Clang, MSVC, and ICC can generate the instructions I want, but GCC does not. You can switch between GCC and Clang in [godbolt](https://godbolt.org/z/8vjsYq ) to see the difference. The `asm` is just a workaround for GCC.

https://github.com/ibireme/yyjson/blob/41069b2bcb628c7094dfe772a9cf7ca56b0c2075/src/yyjson.c#L3956-L3964

https://github.com/ibireme/yyjson/blob/41069b2bcb628c7094dfe772a9cf7ca56b0c2075/src/yyjson.c#L3986-L3995

**Comment by ibireme** [comment]
> Besides detecting IEC 60559 BFP, your fast math detection also does some good in the best effort manner to prevent such failure, however:
> 
> * There can be detection of `__STDC_IEC_60559_BFP__` for future implementations.
> * `#warning` is not conforming. It may fail with `-pedantic`. (OK, this might be the intended behavior, actually.)
> * `__USE_FAST_MATH__` seems [not reliable](https://reviews.llvm.org/D20481).
> * What about MSVC `/fp:fast` and `_M_FP_FAST`?
> * GCC's `-ffinite-math-only` would be enough to break things up, not captured by `__FAST_MATH__`.
> 
> There are rooms of improvements on both the code and the documentation.

If the user explicitly specifies the `fast fp` flag, then I assume that the user knows what he wants to do, so I just give a warning. But it seems that I'm still lacking quite a few checks. I will try to fix this problem to make all codes work correctly without checking the `fast fp` flag.

**Comment by ibireme** [comment]
Released: https://github.com/ibireme/yyjson/releases/tag/0.5.0
