### ISSUE TITLE
Winxp VC6 not support?

### ISSUE THREAD

**Issue by winxxp** [ibireme/yyjson#55]
**Describe the bug**

**Your environment**
 - OS: winxp
 - Compiler: vc6 sp6

**Additional context**

`
--------------------Configuration: testyyjson - Win32 Debug--------------------
Compiling...
yyjson.c
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(2534) : error C2485: 'noinline' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(2717) : error C2485: 'noinline' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(4020) : error C2485: 'noinline' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5181) : error C2485: 'align' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5181) : error C2059: syntax error : '('
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5594) : error C2485: 'noinline' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5604) : warning C4244: '=' : conversion from 'unsigned __int64 ' to 'unsigned int ', possible loss of data
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5888) : error C2485: 'align' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5888) : error C2059: syntax error : '('
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5957) : error C2485: 'align' : unrecognized extended attribute
c:\documents and settings\administrator\桌面\testyyjson\yyjson.c(5957) : error C2059: syntax error : '('
执行 cl.exe 时出错.

testyyjson.exe - 1 error(s), 0 warning(s)
`

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/yyjson/commit/1fea0986f29ce26a79e20f375e5dd1efb4a0d1f0 https://github.com/ibireme/yyjson/commit/986ac356473bfc2a4e88a80a731738c7e035e928
