### ISSUE TITLE
vc6.0 mfc  dll  build error

### ISSUE THREAD

**Issue by dapeng17951** [ibireme/yyjson#60]
vc6.0 mfc project
The dll module introduces yyjson and creates a method of write string
.exe module uses methods in the dll module
Dlls compile alone without problems, .exe compilation prompts
JsonTest.obj : error LNK2001: unresolved external symbol _yyjson_mut_doc_free
JsonTest.obj : error LNK2001: unresolved external symbol _yyjson_mut_doc_new
JsonTest.obj : error LNK2001: unresolved external symbol _yyjson_mut_write_opts
JsonTest.obj : error LNK2001: unresolved external symbol _unsafe_yyjson_val_pool_grow
Debug/JsonTest.exe : fatal error LNK1120: 4 unresolved externals

What should I do?

**Comment by ibireme** [comment]
I'm not familiar with the VC6.0 MFC, maybe you can try these two macro:

https://github.com/ibireme/yyjson/blob/41069b2bcb628c7094dfe772a9cf7ca56b0c2075/src/yyjson.h#L79-L85
