### ISSUE TITLE
How can I read json as mutable document

### ISSUE THREAD

**Issue by xiegx94** [ibireme/yyjson#66]
I found there is an API `yysjon_mut_read_file` in readme. But it doesn't exist in `yyjson.h`. Should I copy yyjson_doc as yyjson_mut_doc every times?

**Comment by panyunyi97** [comment]
U should  do a conversion every time as far as I can see.

**Comment by ibireme** [comment]
Yes, you should make a mutable copy, the readme is wrong and has been updated: https://github.com/ibireme/yyjson/commit/68d08a59faff64c598a84e6cc75e9df5699db44a
