### ISSUE TITLE
yyjson_mut_write_val & yyjson_write_val

### ISSUE THREAD

**Issue by TkTech** [ibireme/yyjson#71]
It's fairly typical to want to extract just part of a document, then write it out. However, there's no current way to print a subset of a document without getting the value, making it the new root, and then writing the entire document.

Ex: Writing the result of a `json_merge_patch()`, or writing the result of a `yyjson_mut_get_pointer()`.

**Comment by ibireme** [comment]
I'll add these 2 functions later to allow writing a value without creating new doc.

**Comment by ibireme** [comment]
Added several functions: https://github.com/ibireme/yyjson/commit/32bba1f4fec1b20a563303e67d2abec4324d7544

**Comment by TkTech** [comment]
Fantastic, thanks @ibireme.
