### ISSUE TITLE
Document the memory behaviour of mutable values.

### ISSUE THREAD

**Issue by TkTech** [ibireme/yyjson#8]
In py_yyjson, I've added JSON Pointer support which includes the ability to patch the value at the pointer with another yyjson_mut_val. However, I noticed that removal doesn't automatically free a value, and there appears to be no explicit API to free a value.

This seems to be by design - the pool for a mutable doc can only be created, grown, or freed in its entirety. There's nothing wrong with this approach, but it should be documented that values, once created, cannot be destroyed. Thus yyjson_mut_doc is more suitable for write-once, than mutation of an existing document.

**Comment by ibireme** [comment]
Yes, it should be documented.
Maybe we can add a `free list` to reuse the `yyjson_mut_val`.

**Comment by TkTech** [comment]
Resolved in 79fee93 :)
