### ISSUE TITLE
Cannot read specific JSON input when compiled for 32-bit

### ISSUE THREAD

**Issue by lnkuiper** [ibireme/yyjson#85]
**Describe the bug**
When compiled with flag `-m32` reading the following JSON returns `NULL`. Reading is fine when compiling for 64-bit.

```json
{
    "firstName": "John",
    "lastName": "Smith",
    "isAlive": true,
    "age": 25,
    "address": {
      "streetAddress": "21 2nd Street",
      "city": "New York",
      "state": "NY",
      "postalCode": "10021-3100"
    },
    "phoneNumbers": [
      {
        "type": "home",
        "number": "212 555-1234"
      },
      {
        "type": "office",
        "number": "646 555-4567"
      }
    ],
    "children": [],
    "spouse": null
    }
```

**Your environment**
 - OS: Ubuntu 20.04 x64
 - Compiler: gcc 5.3.1

**Additional context**
DuckDB uses yyjson for its JSON extension. We had no issues with this specific JSON string before (it is part of our tests). I updated yyjson to the latest version, and this issue occurred.

**Comment by ibireme** [comment]
I haven't tested 32bit C++ compilation in CI, maybe there will be bugs.
I'll investigate later.

**Comment by lnkuiper** [comment]
@ibireme Fixing 32-bit bugs is the worst.

Thank you so much for taking the time to do this, and again thank you so much for this project!
