### ISSUE TITLE
yyjson_read_opts doesn't accept const char *

### ISSUE THREAD

**Issue by dan-ryan** [ibireme/yyjson#93]
Any reason why yyjson_read_opts doesn't accept `const char *`?
I have to cast:
```
yyjson_doc *parse(std::string_view inputString) {
    yyjson_read_flag flags = 0;
    yyjson_read_err error;
    auto jsonDoc = yyjson_read_opts((char *)inputString.data(), inputString.length(), flags, nullptr, &error);
```

**Comment by ibireme** [comment]
It's documented here: https://github.com/ibireme/yyjson/blob/31b0bb4b521d9c16b9e56e151fc92c9cb844b6eb/src/yyjson.h#L679-L681

Since this function will modify the input string with the `YYJSON_READ_INSITU` option, this parameter cannot be declared `const`.
