### ISSUE TITLE
memcpy 2 4  maybe slower than "repeat2_incr"

### ISSUE THREAD

**Issue by wj5449** [ibireme/yyjson#98]
Please use English to communicate so that people from other countries can understand it.
i heared about memcpy when copy little string is slower than = 
because of the memcpy use call instrustion.
on my computer memcpy 2  is slower than "repeat2_incr"
[memcpytest.txt](https://github.com/ibireme/yyjson/files/10242153/memcpytest.txt)

**Comment by wj5449** [comment]
i don't know about what value of strlength 
choose which function is faster

**Comment by ibireme** [comment]
The compiler will do the optimization for you, and usually they produce the exact same instructions, see:
https://godbolt.org/z/4nEr4bKbT
