### ISSUE TITLE
custom indent, for example, 2 space indent.

### ISSUE THREAD

**Issue by loynoir** [ibireme/yyjson#99]
**Is your feature request related to a problem? Please describe.**
Custom indent, for example, 2 space indent.

**Describe the solution you'd like**
Like js
```js
JSON.stringify(foobar,null,2)
```

Or like jansson
```c
json_dumps(root, (size_t)JSON_INDENT(2));
```

**Describe alternatives you've considered**
`YYJSON_WRITE_PRETTY_TWO_SPACES`

**Additional context**

**Comment by ibireme** [comment]
I have added the `YYJSON_WRITE_PRETTY_TWO_SPACES` flag: https://github.com/ibireme/yyjson/commit/eff456db72844839f248cdaef5b20ae58669b4c4. It doesn't affect performance in benchmark tests.

Supporting variable length indent may cause some performance degradation, so I have not implemented it.
